trigger:
- dependabot/maven/com.diffplug.spotless-spotless-maven-plugin-3.0.0

pool:
  name: Default
  demands:
    - agent.name -equals EC2AMAZ-JL1SCA1

steps:
- checkout: self

# Install Trivy (Windows)
- powershell: |
    if (-not (Get-Command trivy -ErrorAction SilentlyContinue)) {
      Invoke-WebRequest `
        -Uri https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_windows-64bit.zip `
        -OutFile trivy.zip

      Expand-Archive trivy.zip -DestinationPath trivy
      Move-Item trivy\trivy.exe C:\Windows\System32\trivy.exe
    }

    trivy --version
  displayName: 'Install Trivy'

# Run Trivy Scan
- powershell: |
    trivy fs `
      --severity HIGH,CRITICAL `
      --exit-code 1 `
      --no-progress `
      .
  displayName: 'Run Trivy SCA Scan'
