trigger:
- dependabot/maven/com.diffplug.spotless-spotless-maven-plugin-3.0.0

pool:
  name: Default
  demands:
    - agent.name -equals EC2AMAZ-G4LHFD3

steps:
- checkout: self

# Install Trivy (Windows - Version 0.68.2)
- powershell: |
    if (-not (Get-Command trivy -ErrorAction SilentlyContinue)) {

      $trivyVersion = "0.68.2"
      $trivyZip = "trivy_$($trivyVersion)_windows-64bit.zip"
      $trivyUrl = "https://github.com/aquasecurity/trivy/releases/download/v$trivyVersion/$trivyZip"

      Write-Host "Downloading Trivy from $trivyUrl"

      Invoke-WebRequest -Uri $trivyUrl -OutFile trivy.zip

      Expand-Archive trivy.zip -DestinationPath trivy -Force
      Copy-Item trivy\trivy.exe C:\Windows\System32\trivy.exe -Force
    }

    trivy --version
  displayName: 'Install Trivy (Windows)'

# Run Trivy Filesystem (SCA) Scan
- powershell: |
    trivy fs `
      --severity HIGH,CRITICAL `
      --exit-code 0 `
      --no-progress `
      .
  displayName: 'Run Trivy SCA Scan'
